name: Build Smart Contract

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true  # penting kalau kamu pakai meteora-dlmm

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Anchor CLI
        run: |
          curl -sSf https://raw.githubusercontent.com/coral-xyz/anchor/master/scripts/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Check Anchor Version
        run: anchor --version

      - name: Build Smart Contract
        run: anchor build

      - name: Upload BPF and IDL
        uses: actions/upload-artifact@v4  # ✅ versi terbaru
        with:
          name: meteora_handler_build
          path: |
            target/deploy/meteora_handler.so
            target/idl/meteora_handler.json

      - name: Decode Devnet Keypair
        run: |
          echo "${{ secrets.DEVNET_DEPLOYER_KEYPAIR }}" | base64 -d > deployer.json

      - name: Deploy to Devnet
        run: |
          solana config set --url https://api.devnet.solana.com
          solana-keygen recover -o ~/.config/solana/id.json file://deployer.json
          anchor deploy
